export const validArchetypes = [
  "/Assault Mode",
  "@Ignister",
  "A.I.",
  "Abyss Actor",
  "Abyss Script",
  "Abyss-",
  "Adamancipator",
  "Advanced Crystal Beast",
  "Adventurer Token",
  "Aesir",
  "Aether",
  "Alien",
  "Allure Queen",
  "Ally of Justice",
  "Altergeist",
  "Amazement",
  "Amazoness",
  "Amorphage",
  "Ancient Gear",
  "Ancient Gear Golem",
  "Ancient Warriors",
  "Apoqliphort",
  "Appliancer",
  "Aquaactress",
  "Aquamirror",
  "Aquarium",
  "Arcana Force",
  "Archfiend",
  "Armed Dragon",
  "Aroma",
  "Artifact",
  "Artorigus",
  "Assault Blackwing",
  "Atlantean",
  "Attraction",
  "B.E.S.",
  "Bamboo Sword",
  "Barbaros",
  "Barian's",
  "Batteryman",
  "Battlewasp",
  "Battlin' Boxer",
  "Battlin' Boxing",
  "Beetrooper",
  "Black Luster Soldier",
  "Blackwing",
  "Blaze Accelerator",
  "Blue-Eyes",
  "Bonding",
  "Borrel",
  "Bounzer",
  "Branded",
  "Bujin",
  "Burning Abyss",
  "Buster Blader",
  "Butterspy",
  "Bystial",
  "Celtic Guard",
  "Mask Change",
  "Chaos",
  "Charmer",
  "Chemicritter",
  "Chronomaly",
  "Chrysalis",
  "Cipher",
  "Cipher Dragon",
  "Clear Wing",
  "Cloudian",
  "Code Talker",
  "Codebreaker",
  "Constellar",
  "Crusadia",
  "Crystal",
  "Crystal Beast",
  "Crystron",
  "Cubic",
  "CXyz",
  "Cyber",
  "Cyber Angel",
  "Cyber Dragon",
  "Cyberdark",
  "Cynet",
  "D/D",
  "D/D/D",
  "Danger!",
  "Dante",
  "Dark Contract",
  "Dark Magician",
  "Dark Magician Girl",
  "Dark Scorpion",
  "Dark World",
  "Darklord",
  "Deskbot",
  "Despia",
  "Destiny HERO",
  "Destruction Sword",
  "Dinomist",
  "Dinomorphia",
  "Dinowrestler",
  "Djinn",
  "Dododo",
  "Dogmatika",
  "Doll Monster",
  "Doodle Beast",
  "Doodlebook",
  "Dracoslayer",
  "Dracoverlord",
  "Dragonmaid",
  "Dragunity",
  "Dream Mirror",
  "Drytron",
  "Dual Avatar",
  "Duston",
  "Earthbound",
  "Earthbound Immortal",
  "Edge Imp",
  "Elder Entity",
  "Eldlich",
  "Eldlixir",
  "Elemental HERO",
  "Elemental Lord",
  "Elementsaber",
  "Empowered Warrior",
  "Endymion",
  "Evil Eye",
  "Evil HERO",
  "Evil★Twin",
  "Evolsaur",
  "Evoltile",
  "Evolution Pill",
  "Evolzar",
  "Exodia",
  "Exosister",
  "Eyes Restrict",
  "F.A.",
  "Fabled",
  "Familiar-Possessed",
  "Favorite",
  "Fire Fist",
  "Fire Formation",
  "Fire King",
  "Fire King Avatar",
  "Firewall",
  "Fishborg",
  "Flamvell",
  "Floowandereeze",
  "Flower Cardian",
  "Fluffal",
  "Forbidden",
  "Forbidden One",
  "Fortune Fairy",
  "Fortune Lady",
  "Fossil",
  "Frightfur",
  "Frog",
  "Fur Hire",
  "Fusion",
  "Fusion Dragon",
  "G Golem",
  "Gadget",
  "Gagaga",
  "Gaia The Fierce Knight",
  "Galaxy",
  "Galaxy-Eyes",
  "Galaxy-Eyes Tachyon Dragon",
  "Gandora",
  "Gate Guardian",
  "Geargia",
  "Geargiano",
  "Gem-",
  "Gem-Knight",
  "Generaider",
  "Genex",
  "Ghostrick",
  "Ghoti",
  "Gimmick Puppet",
  "Gishki",
  "Gladiator Beast",
  "Goblin",
  "Gogogo",
  "Gold Pride",
  "Golden Land",
  "Gottoms",
  "Gouki",
  "GranSolfachord",
  "Gravekeeper's",
  "Graydle",
  "Guardian",
  "Gunkan",
  "Gusto",
  "Harpie",
  "Hazy",
  "Hazy Flame",
  "Heraldic Beast",
  "Heraldry",
  "HERO",
  "Heroic",
  "Heroic Challenger",
  "Hieratic",
  "Hole",
  "Horus",
  "Horus the Black Flame Dragon",
  "Hyperion",
  "Ice Barrier",
  "Icejade",
  "Igknight",
  "Impcantation",
  "Infernity",
  "Infernoble Arms",
  "Infernoble Knight",
  "Infernoid",
  "Infestation",
  "Infinitrack",
  "Inmato",
  "Invoked",
  "Inzektor",
  "Iron Chain",
  "Jinzo",
  "Junk",
  "Jurrac",
  "Kaiju",
  "Kairyu-Shin",
  "Karakuri",
  "Kashtira",
  "Ki-sikil",
  "Knightmare",
  "Koa'ki Meiru",
  "Kozmo",
  "Krawler",
  "Kuriboh",
  "Labrynth",
  "Lady of Lament",
  "Laundsallyn",
  "Laval",
  "Legendary Knight",
  "Libromancer",
  "Lightsworn",
  "Lil-la",
  "Live☆Twin",
  "Lswarm",
  "Lunalight",
  "LV",
  "Lyrilusc",
  "Machina",
  "Machine Angel",
  "Madolche",
  "Magical Musket",
  "Magician",
  "Magician Girl",
  "Magikey",
  "Magistus",
  "Magna Warrior",
  "Magnet Warrior",
  "Majespecter",
  "Majestic",
  "Malefic",
  "Malicevorous",
  "Mannadium",
  "Marincess",
  "Masked HERO",
  "Materiactor",
  "Mathmech",
  "Mayakashi",
  "Mecha Phantom Beast",
  "Megalith",
  "Mekk-Knight",
  "Meklord",
  "Meklord Army",
  "Meklord Astro",
  "Meklord Emperor",
  "Melffy",
  "Melodious",
  "Melodious Maestra",
  "Mermail",
  "Metalfoes",
  "Metaphys",
  "Mikanko",
  "Mist Valley",
  "Mokey Mokey",
  "Monarch",
  "Morphtronic",
  "Mystical Beast of the Forest",
  "Mystical Spirit of the Forest",
  "Mythical Beast",
  "Myutant",
  "Naturia",
  "Necrovalley",
  "Nekroz",
  "Nemeses",
  "Nemleria",
  "Neo Space",
  "Neo-Spacian",
  "Neos",
  "Nephthys",
  "Nimble",
  "Ninja",
  "Ninjitsu Art",
  "Nitro",
  "Noble Arms",
  "Noble Knight",
  "Nordic",
  "Nordic Alfar",
  "Nordic Ascendant",
  "Nordic Beast",
  "Nordic Relic",
  "Nouvelles",
  "Number",
  "Number C",
  "Numeron",
  "Numeron Gate",
  "Odd-Eyes",
  "Ogdoadic",
  "Ojama",
  "Old Entity",
  "Onomat",
  "Orcust",
  "Outer Entity",
  "P.U.N.K.",
  "Paleozoic",
  "Palladium",
  "Parshath",
  "Patissciel",
  "Pendulum",
  "Pendulum Dragon",
  "Pendulumgraph",
  "Penguin",
  "Performage",
  "Performapal",
  "Phantasm",
  "Phantasm Spiral",
  "Phantom Beast",
  "Phantom Knights",
  "Photon",
  "Plunder Patroll",
  "Polymerization",
  "Possessed",
  "Potan",
  "Power Tool",
  "Prank-Kids",
  "Predap",
  "Predaplant",
  "Prediction Princess",
  "Prophecy",
  "PSY-Frame",
  "PSY-Framegear",
  "Puppet",
  "Purrely",
  "Qli",
  "R-Genex",
  "Raidraptor",
  "Rainbow Bridge",
  "Rank-Down-Magic",
  "Rank-Up-Magic",
  "Reactor",
  "Rebellion",
  "Recipe",
  "Red Dragon Archfiend",
  "Red-Eyes",
  "Relinquished",
  "Reptilianne",
  "Rescue-ACE",
  "Resonator",
  "Rikka",
  "Ritual Beast",
  "Ritual Beast Tamer",
  "Ritual Beast Ulti",
  "Roid",
  "Rokket",
  "Roland",
  "Rose",
  "Rose Dragon",
  "Runick",
  "S-Force",
  "Saber",
  "Salamangreat",
  "Scareclaw",
  "Scrap",
  "Sea Stealth",
  "Secret Six Samurai",
  "Seventh",
  "Shaddoll",
  "Shien",
  "Shiranui",
  "Shiranui Spectralsword",
  "Silent Magician",
  "Silent Swordsman",
  "Simorgh",
  "Six Samurai",
  "Sky Striker",
  "Sky Striker Ace",
  "Skyblaster",
  "Skyscraper",
  "Smile",
  "Solfachord",
  "Speedroid",
  "Spellbook",
  "Sphinx",
  "Spirit Message",
  "Spiritual Beast",
  "Spiritual Earth Art",
  "Spiritual Fire Art",
  "Spiritual Water Art",
  "Spiritual Wind Art",
  "Spright",
  "Springans",
  "Sprout",
  "SPYRAL",
  "SPYRAL GEAR",
  "SPYRAL MISSION",
  "Star Seraph",
  "Stardust",
  "Starry Knight",
  "Starving Venom",
  "Stealth Kragen",
  "Steelswarm",
  "Stellarknight",
  "Subterror",
  "Subterror Behemoth",
  "Sunavalon",
  "Sunseed",
  "Sunvine",
  "Super Defense Robot",
  "Super Quant",
  "Super Quantal Mech Beast",
  "Super Quantum",
  "Superheavy Samurai",
  "Superheavy Samurai Soul",
  "Supreme King Dragon",
  "Supreme King Gate",
  "Swordsoul",
  "Sylvan",
  "Symphonic Warrior",
  "Synchro",
  "Synchro Dragon",
  "Synchron",
  "T.G.",
  "Tearlaments",
  "Tellarknight",
  "Tenyi",
  "The Agent",
  "The Phantom Knights",
  "The Weather",
  "Therion",
  "Thunder Dragon",
  "Time Thief",
  "Timelord",
  "Tindangle",
  "Toon",
  "Transcendosaurus",
  "Trap Hole",
  "Traptrix",
  "Tri-Brigade",
  "Triamid",
  "Trickstar",
  "True Draco",
  "U.A.",
  "Ultimate Crystal",
  "Umbral Horror",
  "Unchained",
  "Unchained Soul",
  "Ursarctic",
  "Utopia",
  "Utopic",
  "Utopic Future",
  "Valkyrie",
  "Vampire",
  "Vanquish Soul",
  "Vaylantz",
  "Vehicroid",
  "Vendread",
  "Venom",
  "Vernusylph",
  "Virtual World",
  "Virtual World Gate",
  "Vision HERO",
  "Void",
  "Volcanic",
  "Vylon",
  "War Rock",
  "Warrior",
  "Watt",
  "Welcome Labrynth",
  "Wind-Up",
  "Windwitch",
  "Winged Kuriboh",
  "Wingman",
  "Witchcrafter",
  "World Chalice",
  "World Legacy",
  "Worm",
  "X-Saber",
  "Xyz",
  "Xyz Dragon",
  "Yang Zing",
  "Yosenju",
  "Z-ONE",
  "Zefra",
  "Zexal",
  "Zoodiac",
  "ZS -",
  "Zubaba",
  "ZW -"
];